export * from './articles.service';
import { ArticlesService } from './articles.service';
export * from './authentications.service';
import { AuthenticationsService } from './authentications.service';
export * from './categories.service';
import { CategoriesService } from './categories.service';
export * from './clients.service';
import { ClientsService } from './clients.service';
export * from './commandeClients.service';
import { CommandeClientsService } from './commandeClients.service';
export * from './commandeFournisseurs.service';
import { CommandeFournisseursService } from './commandeFournisseurs.service';
export * from './entreprises.service';
import { EntreprisesService } from './entreprises.service';
export * from './fournisseurs.service';
import { FournisseursService } from './fournisseurs.service';
export * from './mvtStocks.service';
import { MvtStocksService } from './mvtStocks.service';
export * from './photo.service';
import { PhotoService } from './photo.service';
export * from './utilisateurs.service';
import { UtilisateursService } from './utilisateurs.service';
export * from './ventes.service';
import { VentesService } from './ventes.service';
export const APIS = [ArticlesService, AuthenticationsService, CategoriesService, ClientsService, CommandeClientsService, CommandeFournisseursService, EntreprisesService, FournisseursService, MvtStocksService, PhotoService, UtilisateursService, VentesService];
