/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { CategoryDto } from './categoryDto';


export interface ArticleDto { 
    id?: number;
    codeArticle?: string;
    designation?: string;
    description?: string;
    format?: string;
    prixUnitaireHt?: number;
    prixVenteUnitaireHt?: number;
    tauxTva?: number;
    prixUnitaireTtc?: number;
    prixVenteUnitaireTtc?: number;
    marge?: number;
    photo?: string;
    category?: CategoryDto;
    idEntreprise?: number;
}

