/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClientDto } from './clientDto';
import { LigneCommandeClientDto } from './ligneCommandeClientDto';


export interface CommandeClientDto { 
    id?: number;
    code?: string;
    dateCommande?: string;
    idEntreprise?: number;
    etatCommande?: CommandeClientDto.EtatCommandeEnum;
    etat?: CommandeClientDto.EtatEnum;
    client?: ClientDto;
    ligneCommandeClients?: Array<LigneCommandeClientDto>;
    commandeLivree?: boolean;
}
export namespace CommandeClientDto {
    export const EtatCommandeEnum = {
        ProFormat: 'PRO_FORMAT',
        Confirmee: 'CONFIRMEE',
        Vendu: 'VENDU',
        Livree: 'LIVREE',
        Annulee: 'ANNULEE'
    } as const;
    export type EtatCommandeEnum = typeof EtatCommandeEnum[keyof typeof EtatCommandeEnum];
    export const EtatEnum = {
        EtatDocumentProFormat: 'EtatDocument.PRO_FORMAT',
        EtatDocumentConfirmee: 'EtatDocument.CONFIRMEE',
        EtatDocumentVendue: 'EtatDocument.VENDUE',
        EtatDocumentLivree: 'EtatDocument.LIVREE',
        EtatDocumentAnnulee: 'EtatDocument.ANNULEE'
    } as const;
    export type EtatEnum = typeof EtatEnum[keyof typeof EtatEnum];
}


