/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneCommandeFournisseurDto } from './ligneCommandeFournisseurDto';
import { FournisseurDto } from './fournisseurDto';


export interface CommandeFournisseurDto { 
    id?: number;
    code?: string;
    dateCommande?: string;
    etatCommande?: CommandeFournisseurDto.EtatCommandeEnum;
    etat?: CommandeFournisseurDto.EtatEnum;
    fournisseur?: FournisseurDto;
    idEntreprise?: number;
    ligneCommandeFournisseurs?: Array<LigneCommandeFournisseurDto>;
    commandeLivree?: boolean;
}
export namespace CommandeFournisseurDto {
    export const EtatCommandeEnum = {
        ProFormat: 'PRO_FORMAT',
        Confirmee: 'CONFIRMEE',
        Vendu: 'VENDU',
        Livree: 'LIVREE',
        Annulee: 'ANNULEE'
    } as const;
    export type EtatCommandeEnum = typeof EtatCommandeEnum[keyof typeof EtatCommandeEnum];
    export const EtatEnum = {
        EtatDocumentProFormat: 'EtatDocument.PRO_FORMAT',
        EtatDocumentConfirmee: 'EtatDocument.CONFIRMEE',
        EtatDocumentVendue: 'EtatDocument.VENDUE',
        EtatDocumentLivree: 'EtatDocument.LIVREE',
        EtatDocumentAnnulee: 'EtatDocument.ANNULEE'
    } as const;
    export type EtatEnum = typeof EtatEnum[keyof typeof EtatEnum];
}


