/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneCommandeFournisseurDto } from './ligneCommandeFournisseurDto';
import { FournisseurDto } from './fournisseurDto';


export interface CommandeFournisseurDto { 
    id?: number;
    code?: string;
    dateCommande?: string;
    etatCommande?: CommandeFournisseurDto.EtatCommandeEnum;
    fournisseur?: FournisseurDto;
    idEntreprise?: number;
    ligneCommandeFournisseurs?: Array<LigneCommandeFournisseurDto>;
    commandeLivree?: boolean;
}
export namespace CommandeFournisseurDto {
    export const EtatCommandeEnum = {
        Brouillon: 'BROUILLON',
        EnPreparation: 'EN_PREPARATION',
        Validee: 'VALIDEE',
        Livree: 'LIVREE'
    } as const;
    export type EtatCommandeEnum = typeof EtatCommandeEnum[keyof typeof EtatCommandeEnum];
}


