/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AdresseDto } from './adresseDto';


export interface FournisseurDto { 
    id?: number;
    nom?: string;
    prenom?: string;
    photo?: string;
    email?: string;
    numTel?: string;
    adresse?: AdresseDto;
    idEntreprise?: number;
}

