/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { VenteDto } from './venteDto';
import { ArticleDto } from './articleDto';


export interface LigneVenteDto { 
    id?: number;
    quantite?: number;
    prixUnitaire?: number;
    idEntreprise?: number;
    article?: ArticleDto;
    vente?: VenteDto;
}

