/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleDto } from './articleDto';


export interface LigneCommandeFournisseurDto { 
    id?: number;
    quantite?: number;
    prixUnitaireTtc?: number;
    idEntreprise?: number;
    article?: ArticleDto;
}

