/**
 * Gestion de stock REST API documentation
 *
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleDto } from './articleDto';


export interface MvtStockDto {
    id?: number;
    dateMvt?: string;
    quantite?: number;
    codeCorrection?: number;
    idEntreprise?: number;
    article?: ArticleDto;
    typeMvt?: MvtStockDto.TypeMvtEnum;
    sourceMvt?: MvtStockDto.SourceMvtEnum;
    codeSource?: string;
}
export namespace MvtStockDto {
    export const TypeMvtEnum = {
        Entree: 'ENTREE',
        Sortie: 'SORTIE',
        SortieVte: 'SORTIE_VTE',
        CorrectionPos: 'CORRECTION_POS',
        CorrectionNeg: 'CORRECTION_NEG',
        CorrectionPosVenteRed: 'CORRECTION_POS_VENTE_RED',
        CorrectionNegVenteAug: 'CORRECTION_NEG_VENTE_AUG',
        CorrectionNegRetourFournisseur: 'CORRECTION_NEG_RETOUR_FOURNISSEUR'
    } as const;
    export type TypeMvtEnum = typeof TypeMvtEnum[keyof typeof TypeMvtEnum];
    export const SourceMvtEnum = {
        CommandeClient: 'COMMANDE_CLIENT',
        CommandeFournisseur: 'COMMANDE_FOURNISSEUR',
        Vente: 'VENTE',
        CorrectionStock: 'CORRECTION_STOCK'
    } as const;
    export type SourceMvtEnum = typeof SourceMvtEnum[keyof typeof SourceMvtEnum];
}


