/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleDto } from './articleDto';


export interface MvtStockDto { 
    id?: number;
    dateMvt?: string;
    quantite?: number;
    codeCorrection?: string;
    idEntreprise?: number;
    article?: ArticleDto;
    typeMvt?: MvtStockDto.TypeMvtEnum;
    type?: MvtStockDto.TypeEnum;
    sourceMvt?: MvtStockDto.SourceMvtEnum;
    source?: MvtStockDto.SourceEnum;
    codeSource?: string;
}
export namespace MvtStockDto {
    export const TypeMvtEnum = {
        Entree: 'ENTREE',
        Sortie: 'SORTIE',
        SortieVte: 'SORTIE_VTE',
        CorrectionPos: 'CORRECTION_POS',
        CorrectionNeg: 'CORRECTION_NEG',
        CorrectionPosVenteRed: 'CORRECTION_POS_VENTE_RED',
        CorrectionNegVenteAug: 'CORRECTION_NEG_VENTE_AUG',
        CorrectionNegRetourFournisseur: 'CORRECTION_NEG_RETOUR_FOURNISSEUR'
    } as const;
    export type TypeMvtEnum = typeof TypeMvtEnum[keyof typeof TypeMvtEnum];
    export const TypeEnum = {
        ArticleLivrParLeFournisseur: 'Article livré par le fournisseur',
        ArticleCommandConfirm: 'Article à command confirmé',
        ArticleVenduAuClient: 'Article vendu au client',
        CorrectionPrCompenserErreurDeComptage: 'Correction pr compenser erreur de comptage',
        CorrectionPourConsidrerUnePerte: 'Correction pour considérer une perte',
        CorrectionPrRetourDunArticleVendu: 'Correction pr retour d\'un article vendu',
        CorrectionPrLajoutDuNbreDunProduitVendu: 'Correction pr l\'ajout du nbre d\'un produit vendu',
        CorrectionPrLeRetourAuFournisseurDunProduitAchet: 'Correction pr le retour au fournisseur d\'un produit acheté'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const SourceMvtEnum = {
        CommandeClient: 'COMMANDE_CLIENT',
        CommandeFournisseur: 'COMMANDE_FOURNISSEUR',
        Vente: 'VENTE',
        CorrectionStock: 'CORRECTION_STOCK'
    } as const;
    export type SourceMvtEnum = typeof SourceMvtEnum[keyof typeof SourceMvtEnum];
    export const SourceEnum = {
        CommandeDesArticlesParUnClient: 'Commande des articles par un client',
        CommandeDesArticlesParUnFournisseur: 'Commande des articles par un fournisseur',
        VenteDesArticles: 'Vente des articles',
        CorrectionDuStockSuiteUnVnement: 'Correction du stock suite à un évènement'
    } as const;
    export type SourceEnum = typeof SourceEnum[keyof typeof SourceEnum];
}


