/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ArticleDto } from './articleDto';


export interface MvtStockDto { 
    id?: number;
    dateMvt?: string;
    quantite?: number;
    idEntreprise?: number;
    article?: ArticleDto;
    typeMvt?: MvtStockDto.TypeMvtEnum;
    type?: MvtStockDto.TypeEnum;
    sourceMvt?: MvtStockDto.SourceMvtEnum;
    source?: MvtStockDto.SourceEnum;
    codeSource?: string;
}
export namespace MvtStockDto {
    export const TypeMvtEnum = {
        Entree: 'ENTREE',
        Sortie: 'SORTIE',
        SortieVte: 'SORTIE_VTE',
        CorrectionPos: 'CORRECTION_POS',
        CorrectionNeg: 'CORRECTION_NEG',
        CorrectionPosVenteRed: 'CORRECTION_POS_VENTE_RED',
        CorrectionNegVenteAug: 'CORRECTION_NEG_VENTE_AUG',
        CorrectionNegRetourFournisseur: 'CORRECTION_NEG_RETOUR_FOURNISSEUR'
    } as const;
    export type TypeMvtEnum = typeof TypeMvtEnum[keyof typeof TypeMvtEnum];
    export const TypeEnum = {
        ETypeDocumentEntree: 'ETypeDocument.ENTREE',
        ETypeDocumentSortie: 'ETypeDocument.SORTIE',
        ETypeDocumentSortieVte: 'ETypeDocument.SORTIE_VTE',
        ETypeDocumentCorrectionPos: 'ETypeDocument.CORRECTION_POS',
        ETypeDocumentCorrectionNeg: 'ETypeDocument.CORRECTION_NEG',
        ETypeDocumentCorrectionPosVenteRed: 'ETypeDocument.CORRECTION_POS_VENTE_RED',
        ETypeDocumentCorrectionNegVenteAug: 'ETypeDocument.CORRECTION_NEG_VENTE_AUG',
        ETypeDocumentCorrectionNegRetourFournisseur: 'ETypeDocument.CORRECTION_NEG_RETOUR_FOURNISSEUR'
    } as const;
    export type TypeEnum = typeof TypeEnum[keyof typeof TypeEnum];
    export const SourceMvtEnum = {
        CommandeClient: 'COMMANDE_CLIENT',
        CommandeFournisseur: 'COMMANDE_FOURNISSEUR',
        Vente: 'VENTE',
        CorrectionStock: 'CORRECTION_STOCK'
    } as const;
    export type SourceMvtEnum = typeof SourceMvtEnum[keyof typeof SourceMvtEnum];
    export const SourceEnum = {
        ESourceDocumentCommandeClient: 'ESourceDocument.COMMANDE_CLIENT',
        ESourceDocumentCommandeFournisseur: 'ESourceDocument.COMMANDE_FOURNISSEUR',
        ESourceDocumentVente: 'ESourceDocument.VENTE',
        ESourceDocumentCorrectionStock: 'ESourceDocument.CORRECTION_STOCK'
    } as const;
    export type SourceEnum = typeof SourceEnum[keyof typeof SourceEnum];
}


