/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface RolesDto { 
    id?: number;
    roleName?: RolesDto.RoleNameEnum;
}
export namespace RolesDto {
    export const RoleNameEnum = {
        Caissier: 'CAISSIER',
        Manager: 'MANAGER',
        Directeur: 'DIRECTEUR',
        Admin: 'ADMIN'
    } as const;
    export type RoleNameEnum = typeof RoleNameEnum[keyof typeof RoleNameEnum];
}


