/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { EntrepriseDto } from './entrepriseDto';
import { RolesDto } from './rolesDto';
import { AdresseDto } from './adresseDto';


export interface UtilisateurDto { 
    id?: number;
    nom?: string;
    statut?: string;
    email?: string;
    numTel?: string;
    dateDeNaissance?: string;
    motDePasse?: string;
    photo?: string;
    adresse?: AdresseDto;
    entreprise?: EntrepriseDto;
    roles?: Array<RolesDto>;
}

