/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface VenteDto { 
    id?: number;
    code?: string;
    dateVente?: string;
    commentaire?: string;
    idEntreprise?: number;
}

