/**
 * Gestion de stock REST API documentation
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { LigneVenteDto } from './ligneVenteDto';
import { ClientDto } from './clientDto';


export interface VenteDto { 
    id?: number;
    code?: string;
    dateVente?: string;
    paymentType?: VenteDto.PaymentTypeEnum;
    client?: ClientDto;
    idEntreprise?: number;
    ligneVentes?: Array<LigneVenteDto>;
}
export namespace VenteDto {
    export const PaymentTypeEnum = {
        OrangeMoney: 'ORANGE_MONEY',
        MobileMoney: 'MOBILE_MONEY',
        BankTransfer: 'BANK_TRANSFER',
        Cash: 'CASH'
    } as const;
    export type PaymentTypeEnum = typeof PaymentTypeEnum[keyof typeof PaymentTypeEnum];
}


